# Automatically generated by configure - do not modify
SRC_PATH=/home/fanning/workspace/raspi3-tutorial-master/01_bareminimum/qemu/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
